// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projectwerk.Infrastructure.Data;

#nullable disable

namespace Projectwerk.Infrastructure.Migrations
{
    [DbContext(typeof(RetroDbContext))]
    [Migration("20240507164700_rentalPricePerWeek")]
    partial class rentalPricePerWeek
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Projectwerk.Infrastructure.Models.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("GameID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GameId"));

                    b.Property<string>("Category")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ConsoleType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CoverImage")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<decimal?>("RentalPricePerWeek")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("GameId")
                        .HasName("PK__Game__2AB897DD9C42FE40");

                    b.ToTable("Game");
                });

            modelBuilder.Entity("Projectwerk.Infrastructure.Models.Rental", b =>
                {
                    b.Property<int>("RentalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RentalID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RentalId"));

                    b.Property<DateTime>("EndRentalPeriod")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GameId")
                        .HasColumnType("int")
                        .HasColumnName("GameID");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("NumberOfExtensions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<decimal?>("RentalPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime>("StartRentalPeriod")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("RentalId")
                        .HasName("PK__Rental__9700596305A5A441");

                    b.HasIndex(new[] { "GameId" }, "IX_Rental_GameID");

                    b.HasIndex(new[] { "UserId" }, "IX_Rental_UserID");

                    b.ToTable("Rental");
                });

            modelBuilder.Entity("Projectwerk.Infrastructure.Models.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReservationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationId"));

                    b.Property<int?>("GameId")
                        .HasColumnType("int")
                        .HasColumnName("GameID");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("PickupDate")
                        .HasColumnType("date");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("ReservationId")
                        .HasName("PK__Reservat__B7EE5F04AD3AF1A4");

                    b.HasIndex(new[] { "GameId" }, "IX_Reservation_GameID");

                    b.HasIndex(new[] { "UserId" }, "IX_Reservation_UserID");

                    b.ToTable("Reservation");
                });

            modelBuilder.Entity("Projectwerk.Infrastructure.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Role")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("client");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId")
                        .HasName("PK__User__1788CCACF3B8A4A9");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Projectwerk.Infrastructure.Models.Rental", b =>
                {
                    b.HasOne("Projectwerk.Infrastructure.Models.Game", "Game")
                        .WithMany("Rentals")
                        .HasForeignKey("GameId")
                        .HasConstraintName("FK__Rental__GameID__6442E2C9");

                    b.HasOne("Projectwerk.Infrastructure.Models.User", "User")
                        .WithMany("Rentals")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Rental__UserID__634EBE90");

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Projectwerk.Infrastructure.Models.Reservation", b =>
                {
                    b.HasOne("Projectwerk.Infrastructure.Models.Game", "Game")
                        .WithMany("Reservations")
                        .HasForeignKey("GameId")
                        .HasConstraintName("FK__Reservati__GameI__5F7E2DAC");

                    b.HasOne("Projectwerk.Infrastructure.Models.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Reservati__UserI__5E8A0973");

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Projectwerk.Infrastructure.Models.Game", b =>
                {
                    b.Navigation("Rentals");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("Projectwerk.Infrastructure.Models.User", b =>
                {
                    b.Navigation("Rentals");

                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
